language: objective-c
osx_image: xcode12.2
branches:
  only:
  - main
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
script:
- fastlane scan
- fastlane travis_testflight
